# Generated by Django 5.2.1 on 2026-05-09 21:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('RANDOM_THOUGHTS', 'Random Thoughts'), ('SCHOOL', 'School'), ('PERSONAL', 'Personal')], max_length=64, unique=True)),
                ('color', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
    ]
