services:
  backend:
    build:
      context: ./backend
    container_name: turbo-notes-backend
    working_dir: /app
    command: tail -f /dev/null
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: turbo_notes
      DATABASE_USER: turbo_user
      DATABASE_PASSWORD: turbo_password
      DATABASE_PORT: 5432

  frontend:
    image: node:22-alpine
    container_name: turbo-notes-frontend
    working_dir: /app
    command: tail -f /dev/null
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: turbo-notes-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: turbo_notes
      POSTGRES_USER: turbo_user
      POSTGRES_PASSWORD: turbo_password

volumes:
  postgres_data:
